databricks:
  host: e2-demo-west.cloud.databricks.com
  token: XXXXXX

aws:
  access_key_id: XXXXXX
  secret_access_key: XXXXXX
  bucket:
    name: databricks-web-files
    path: notebooks/{vertical}/{solution_codename}/{file_name}
    link: https://databricks-web-files.s3.us-east-2.amazonaws.com/notebooks

tmp_dir: dist