name: Solution Accelerator Build
env:
  DB_TOKEN: ${{ secrets.DB_TOKEN }}

on:
  workflow_dispatch:
    inputs:
      repository_path:
        description: 'Repository path on E2 field eng'
        required: true
        default: '/Workspace/Repos/antoine.amend@databricks.com/esg-scoring'
      industry_vertical:
        description: 'Industry vertical, can be [fsi, cme, rcg, hls, mnf, cyb]'
        required: true
        default: 'fsi'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      # The first step is obviously to check out the repository
      - name: Checkout project
        uses: actions/checkout@v2

      # We test and package our code against python 3.9 distribution
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

        # we create our own pip cache where dependencies from requirements.txt will be stored
      - name: Configure Python
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            ${{ runner.os }}-pip-

        # Let's install pip and make sure we run against latest version
      - name: Install pip
        run: python -m pip install --upgrade pip

        # And install any dependency required for unit testing
      - name: Install dependencies
        run: pip install -U -r requirements.txt

        # Package and publish solution
      - name: Publish solution accelerator
        run: python databricks.py --vertical ${{ github.event.inputs.industry_vertical }} --path ${{ github.event.inputs.repository_path }}
