name: Solution Accelerator Build

on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      # The first step is obviously to check out the repository
      - name: Checkout project
        uses: actions/checkout@v2

      # We test and package our code against python 3.9 distribution
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

        # we create our own pip cache where dependencies from requirements.txt will be stored
      - name: Configure Python
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            ${{ runner.os }}-pip-

        # Let's install pip and make sure we run against latest version
      - name: Install pip
        run: python -m pip install --upgrade pip

        # And install any dependency required for unit testing
      - name: Install dependencies
        working-directory: ./python
        run: pip install -U -r requirements.txt wheel semver==3.0.2 wheel==0.42.0

        # Here comes the crux of our python development. See core logic in our setup.py file
      - name: Build python dist
        working-directory: ./python
        run: python setup.py clean bdist_wheel
